min_version = "2026.9.14"
monorepo_root = true

[env]
"_.file" = ".env"

[monorepo]
[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "pnpm"]

[settings.npm]
package_manager = "pnpm"

[tools]
"npm:@antfu/ni" = "latest"
turbo = "latest"
