## https://mise.jdx.dev/
min_version = "2026.7.11"

## https://mise.jdx.dev/tasks/monorepo.html
monorepo_root = true

[monorepo]
## explicitly states that we don't have sub-configs (there is still warning as of 2026/08, to revisit later)
config_roots = []

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node", "pnpm"]
## https://mise.jdx.dev/configuration/settings.html#npm-package-manager
npm.package_manager = "pnpm"

[tools]
turbo = "latest"
## https://github.com/antfu-collective/ni
"npm:@antfu/ni" = "latest"


### TO REVIEW

#[deps.pnpm]
#auto = true


#[env]
#"_.file" = ".env"


#[tools."npm:corepack"]
#postinstall = "corepack enable"
#ersion = "latest"
